### ISSUE TITLE
Remove unused toolbars/buttons from ckeditor

### ISSUE THREAD

**Issue by mitch-mitchel** [CCALI/a2jauthor#214]
This items should be removed from the ckeditor toolbar config
![image (1)](https://user-images.githubusercontent.com/11528248/135876519-6473c113-7f73-4d3c-8acf-b639abc3b0a8.png)

**Comment by chasenlehara** [comment]
I wonder if it would make sense to remove these as well:

- Save
- New page

The content templates are kinda weird too; in particular, the “Image and Text” template doesn’t actually insert an image and text… is that intentional?

<img width="439" alt="Screen Shot 2021-10-12 at 2 53 02 PM" src="https://user-images.githubusercontent.com/10070176/137034240-9df744e2-69ae-480d-90d8-23c461975845.png">

Are all of the link options supposed to be available? There are a lot:

<img width="388" alt="Screen Shot 2021-10-12 at 8 55 15 AM" src="https://user-images.githubusercontent.com/10070176/137034355-b71a5272-d8b0-4250-9f66-6a2cb2409748.png">
<img width="391" alt="Screen Shot 2021-10-12 at 8 55 07 AM" src="https://user-images.githubusercontent.com/10070176/137034359-cbea657a-364c-48f2-ac7b-7d4d98266629.png">

**Comment by JessicaFrank** [comment]
Can definitely remove the content templates section. I'll check the links options tomorrow.

**Comment by JessicaFrank** [comment]
@mikemitchel @tobiasnteireho can you think of a reason to keep the save/new page/print option within the rich text element of the CK editor?

**Comment by mitch-mitchel** [comment]
print option maybe, for translations ? save and new page, no

**Comment by janebitovi** [comment]
this was completed previously
<img width="1121" alt="image" src="https://user-images.githubusercontent.com/92131113/174316591-2dc251d8-bc26-4499-bb0d-6f6bf8b67d0e.png">
