### ISSUE TITLE
Advanced Navigation: Step name not needed on every page

### ISSUE THREAD

**Issue by normon66** [CCALI/a2jauthor#243]
Is the current Step name supposed to be included on _every single_ page? On longer pages or those with numerous fields, this can take up valuable screen real estate (especially on mobile, though I have not actually taken a look at staging on mobile).

![image](https://user-images.githubusercontent.com/32527754/146044908-6bc18666-0d8e-4a61-857c-ab36c376c280.png)

This is on staging, though the version shows _A2J 7.0-2021-08-11_

**Comment by janebitovi** [comment]
Per convo with Jessica:
There must be CSS hiding it on desktop view on production because the tag is definitely in dom: https://github.com/CCALI/a2jviewer/blob/production/src/mobile/pages/pages.stache#L18-L24
production screenshot:
![image](https://user-images.githubusercontent.com/92131113/146561362-f47b1d27-7ec4-47ac-aac4-1bf29dc016ad.png)

Tasks:
- [x] Hide it on desktop (leave it in DOM)
- [x] Show it on reduced UI desktop since the illustration sign isn't there
- [x] Show it on mobile

must have broken whatever CSS was hiding it...?
