### ISSUE TITLE
Resizing staging.a2jauthor.org in Preview mode breaks app

### ISSUE THREAD

**Issue by JessicaFrank** [CCALI/a2jauthor#247]
Attempting to simulate mobile view by resizing the browser in preview mode with advanced navigation panel open. Viewer resizes, but blank space for advanced nav panel stays open. Get an error in the console (See image), then can't get back into preview mode. App broken and requires a refresh of the browser. 
![image](https://user-images.githubusercontent.com/7662028/146232255-950dbfe9-f0a5-4f34-8499-dcacdfd26e55.png)

**Comment by janebitovi** [comment]
I was unable to make it crash but I did fix the big empty space problem

That fix (along with many others) is being deployed to staging today

Leaving this open since I technically didn't address the reported crash (since I couldn't reproduce it)
TODO: confirm crash is fixed or provide steps to reproduce on the newest staging deploy

**Comment by janebitovi** [comment]
Hey @JessicaFrank if you can still reproduce this crash on production, could you show me? It seems to be working so this could be closed if you confirm

**Comment by JessicaFrank** [comment]
Can't crash again on production, so closing.
