### ISSUE TITLE
Button that goes "no where" freezes author - no "page does not exist!" message

### ISSUE THREAD

**Issue by normon66** [CCALI/a2jauthor#256]
In the current staging.a2jauthor (which shows version _A2J 7.0-2021-08-11_), if a button click goes to "[no where]", it freezes the editor if you go into Preview mode and click said button. When said button is clicked, the below message is shown in the developer console:
   ![image](https://user-images.githubusercontent.com/32527754/146430996-8eab5038-cddf-4f00-b254-61b006793193.png)

Buttons still change color/mode when you hover over or click them, but they are unresponsive. The only way out appears to be to refresh the page.

I verified that this does _not_ happen in production a2jauthor.org (version _A2J 7.0.5-2021-05-04_), which instead goes to the "This page does not exist!" error and allows you to return to edit mode.

**Comment by janebitovi** [comment]
This causes a popover modal now instead of crashing the app:

![nowhere](https://user-images.githubusercontent.com/92131113/146966206-4b7f6d9c-413f-4b2c-bb22-d84981cc8b30.gif)

Note: The adv nav duplicates the current visitedpage when this happens, which is a bug (that's difficult to fix) that's low priority because it doesn't crash and a bad author button is the precursor

**Comment by janebitovi** [comment]
fixed the duplicate visited page locally, fix can go out with production next week
![nowhere2](https://user-images.githubusercontent.com/92131113/147135276-af2309a9-2402-4ec9-9842-b312e894a0ab.gif)
